#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer --http-status-ignore "999,401,404" --url-ignore "www.linkedin.com, #" ./_site

bundle exec travis encrypt --add deploy.secret_access_key

