language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./.script/cibuild
script: "./.script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production2
sudo: false
deploy:
  provider: s3
  access_key_id: AKIAIB5EFXTQV7UCLM5Q
  secret_access_key:
    secure: NT0966+Eor5NqGf0kz3BgOVWk1SCUcLulBCUtuXacT7R5DI/hBnnrOVj44A+wj1lvy/4Wjr5j13w8nZUW8icd2L09Z+VU0YMV0+JdbRxnovDyWDtRVRAdbXF+Tzwg81xMohW9GFGVoQd+zyjl4gn8eSWHAoYhIdDAkAnyWS2+Aj3pwIOpawg0cWn4cOLrIgf5wvkNntumSe8dE1QSHI/yK/rq4+cj96Yp3XNlqZrj6BcatDw3inLNPbmd/Hbmddevy3Uq+Epxy7+beMY01IRwb1QcRuaF8zKECmt0af8qZCjIYCdQ+VYpYfWrxEH9mZmJSal9xpwSSQ4tZadH4qYnF0BgJSyKrbFpwoP9kosbFsKrZjg8VQ5CzrW0kr+j6BEhMeAPl25mev8oZo+3bDftjwVpTsvg+SUeKRlxJObCYYW+EgxxId08qNaEB6nhGwtK/tVIqJHFLqj8jaqQFvxurV7gcgFoUq3SPsXsTudBlPIxoqzp1z4+vj6irWHzUdzQWc2EU0bB/Z6b1NCt+UigxfQUkvAtUaKn9wKuQr9e+gC3jFN6+Cf7AwicDJoEK4rafUUZyYEcYI1p3vnJATgRNbOIeKw658VP9xt1oBaE43pJnIp/PIEMRpa8hI+MVlqVw8ChQ4hKDvcw7petG4W9/LgaC/LliNnpCgesgi4HeY=
  bucket: ilikhachev.com
  skip_cleanup: true
  local_dir: "./_site"
  region: "us-west-2"
