language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./.script/cibuild
script: "./.script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production2
sudo: false

deploy:
  provider: s3
  access_key_id: AKIAIKF2HFKMVEXQVL6A
  secret_access_key: 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 
  bucket: ilikhachev.com
  skip_cleanup: true
  local_dir: "./_site"
  region: us-west-2
