language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./.script/cibuild
script: "./.script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production2
sudo: false
deploy:
  provider: codedeploy
  access_key_id: AKIAIZBEH5LYLI6G2J2Q
  secret_access_key:
    secure: Cn97Yg1snswTRTrbRvA1aFHiPlkhNXv/ZqSIOrrKkQcKS6SgHJDEdbf/vxToKQlefrSVdYeyVXivggofudl/QpQKvAR22h/uHFOLW2b6VJYegjqklo3qoaZ8c6OcgOxGCp1oJqgNXBxWccRVKokBfVh8DA+4MrZupO7oiAOC4pWkUZX6U7cdEZQ8MAX9+HLsNvsjW8N0kKZByyKbrHyj9fhREyJhCZna9R6n/C0uaxD+91Oewifrm2Kmc91fhXckP3geG2rNHcnxO+Tfk8BOuGi6XgIJQux7d5XcbVOA8akylfK4/I+AhxPmwNo33J0wMOv7E3K8JNToKutQS4CW8+yGO1EhlC/9N4VyubULgqLRdSoftzrOxS8nzdGY3nt7z9EWjXYxmW53puL7sKWqsi0aNy62cTjfW01XTFOfpqqhtmdyGTkrDiED0wc+oIUBytMVLQ/aVc+LG9FGVzAjh+AmKa48x5X8YCiWR12BkxWgWQV1B4Ow0GygezrnCJqnzylACSO/vOU5XJwMYQ2xQrbcLIR5EJgg2rdhktjWgN0meM7GiwXJFjaMltIWRKs1HOEjSxiietSb3xLNId9ElFlQeMAqy9fUDmFcTLJlO3Tz9RY4oa3hPGe/Y9tMmDph+DVHTP1D75kzulfjf6uVd4uZAMgjZWg+fboq7s5eBlo=
  bucket: ilikhachev.com
  key: "./site"
  bundle_type: zip
  application: ivli.github.io
  deployment_group: ''
  on:
    repo: ivli/ivli.github.io
