language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./.script/cibuild
script: "./.script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production2
sudo: false
deploy:
  provider: s3
  access_key_id: AKIAJEJLY6CK3NYWWXGQ
  secret_access_key:
    secure: W8si4Nf3l1RQiVOs4Rh+aSqFOypLb+03R8i3zRlppYECzjMRS+YsWMZUd6cbI0gvjwSI8ODPKZyA2V1pJrDsbUyI1zwk47nZ3NwzkOZPX3GuDVGg7Vv2wHvtS0Qj2fbE5U5xb8i/norKr25wGKGj6T19LqUabbljuzKEP9SvxPaIL/S4SRmnkn41ZcTPKCQhId8AIl+FrK2AD1k+HgNkHxshgTfDAR4q4Ml9ooKO9xt5OoYBgyDqEe7KKiEWNE6z5N9otW+O/IszdGuFh9Pdh9hYtKHVxWdB9Q8aZvafGFhoKoaxYs731dBtRG4Mku+vO2nnxIGVGfqqHTf5ZIqANG2cXahoridA2py2M29vI8kBCLP9rRQIfeOr/VnrpON8S+Ee41IOfGpEPJo8m6q+w5FsclGZTWEcq6STMtMir6yov3ZYY9/L9xtXHl+F/ggaTB33hr3pSnFnE0+rLHxsqoyVV73vW/WeWhMmKTfLWEjfKKJUB/rN3WEHbn2zvGBYQsdw2FrbblHh84UO3rkkKBF5lZ1Ffy1KdhiqjcpHjoTYhtJ+4HX86GHuZsI26CUi4wGTczY5UuwWSbR2zYNQgmwAgCvcu5ONDADZ6euuwB+gcckoSagWHUOPuYWKP1IhboTCXwV1AiLTLSbIDjeIPoUgqzzY3ZUy4MK6hoVOGPE=
  bucket: ilikhachev.com
  skip_cleanup: true
  local_dir: "./_site"
  region: us-west-2
  
  
