language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./.script/cibuild
script: "./.script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production2
sudo: false
deploy:
  provider: s3
  access_key_id: AKIAJEJLY6CK3NYWWXGQ
  secret_access_key:
    secure: PXWkbGyAWzU85qp9imfZ7d/ZogbY2SdfSpIr/r8Bts8DBV1B2aGxwCECW4Sf7lzX23c6TiZos4lz7iXnWzF+lqUA9xq0bzfnvg1vGk4v7ECjxy52yCGW5atGUW99rpVIpUa7Vr1YQ37zaxk+tZxKphBfRw9/JlXIFK/kfTFRZc9CyHaVrP3IkM5jAe5DpCA80dS55Ym2vdrx8ecGtG/v8JYtI1WhNBj0wnVO5cKUsPsQCvzbTGK8S2w0vNjh13KcD18BLFWOPmA31gJ7s/F91cuwG5fZQN7ZyOlE/y+G5z5zzAZhy4enEcHhO8aFSS/bP0PvPgUZFxBESYRGCKD9QGHT6Dxf6BUw+nfFyZZIUx4Ric0M++nuAh74wwQApizzjYfwJeHwPMCOpxcpCx3AXUMx7TpIjMZbHTBifCgPm2w5lGjfS7CLGWhv1oI8EukqAaL2mQiRQpmmA7ddYKkXBcifY3Xhb4ATPNanRTeJpmWK4T+7VeU7GNa/BGPQbedKifma/kqBSOAaVWLE/x20skvLkOSFtexhc5q6LUzkgSsjMUSLQVU4YvIROZ4HnkU1MCr3CroAAvSbWW7OBiYfRsXR0xD/lsKHC+aqp09ZpxoQAA0pUw6ZHHYhEyIJLakzob0def2C8GiiRhnKSfANVKpg1rqfOhuQUPQj0GzDHYg=
  bucket: ilikhachev.com
  skip_cleanup: true
  local_dir: "./_site"
  region: us-west-2
