language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./.script/cibuild
script: "./.script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production2
sudo: false
deploy:
  provider: s3
  access_key_id: AKIAJEJLY6CK3NYWWXGQ
  secret_access_key:
    secure: UscEH5z/8KsDAvr21nwPLmfb5qlyy9e3hrbpObjXxVw6jT1iaYDfqc9sNFiDQ+ziZu5EIuSRtYgI+333E9eCKpsLUpB6FyFF1kbcJEWwFC/2UUJzauRIblFtN+LJ4S07U0lHEn/C29DYZBWvqV0JhziLq5ZiZiVJVvXYr7Mk8/U1zpOLSIjqLQdgq7tcBPrlJLIay7OYTiX2N4+9IJKJKSnCq2av0IkJ81x+xAeZNSCT1F0iqj5uEcb+YvTcnbkmR9ixZlVbMAlDwvjRIAJ1a4hssSRxeu6LIS7b6xh3YSuPf2T4R5+PQK/Y6b+HDW+Z3fV1LDmREZRT5I0aCYmZptO4+dUNTEAl2MTQ5R1mB7O65bvAQL9PvCSKzku+R5ORym8yzl35vtNmCGYylHKeOhC43ENsKUUngnaaozxqpWiawB2DxDWdy4f6dBjgRlpkvQWU1B+tcW3yvdVxyhXY813P8WSInLhWBdsPlx0ux+wve68ysd5AdA8YHS/1xHrXj7cpota3nvyYRHK36FkSvjSuRL5IzAnqKBVFXzuWnx+FjSCe4f/+ICwgr4BH7C6vPltSq3gVMDtzInCdP7divswl2QoDXSgjJcbNOi1Pk5UGAgGAv0h0KuTAgig+qjnOW1rG9CTeneybl04rDX+2BUIpcs+aYRzRlX6MPEt6ohg=
  bucket: ilikhachev.com
  skip_cleanup: true
  local_dir: "./_site"
  region: us-west-2
