# Site settings
title: Igor Likhachev home page
name: Igor Likhachev
url: https://ilikhachev.com
# Build settings
markdown: kramdown
##theme: minima
# 
gems:
 ## - html-proofer
 ## - jekyll-seo-tag
 ## - jekyll-press
exclude:
 - Gemfile
 - Gemfile.lock

# Google services
google_analytics: UA-72006658-2
google_analytics2: UA-72006658-3
#User specific content
#Links that will appear in the navbar
primarylinks:
 ##- title: Not_A_Blog ## url: category/blog.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/igorlikhachev
 - title: GitHub
   url: https://github.com/ivli
 - title: Runkeeper
   url: https://runkeeper.com/user/theIgorL  

#List of interesting Github repo/projects to include - optional
github:
 - ivli/roim 
 - ivli/isolevels
 - ivli/ivli.github.io

hobbies:
 - reading
 - skiing both alpine and x-country 
 - biking and skating (asphalt) 
 - music: classical, jazz 
 - and, I am an amateur jazz guitar player 

##blogfeed: category/blog.html
future: true

buildstatus: >
  [![Build Status](https://travis-ci.org/ivli/ivli.github.io.svg?branch=master)](https://travis-ci.org/ivli/ivli.github.io)

extras: ./category/blog.html
##https://drive.google.com/file/d/0B2iEehEHhN35TG5GNld6UEV5VXM/view?usp=drivesdk
