# Site settings
title: Igor Likhachev
name: Igor Likhachev

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/ivli
 - title: LinkedIn
   url: https://www.linkedin.com/in/igorlikhachev

#List of interesting Github repo/projects to include - optional
github:
 - ivli/roim 
 - ivli/Isolevels
  