# Site settings
title: Igor Likhachev home page
name: Igor Likhachev
url: https://ilikhachev.com
# Build settings
markdown: kramdown
##theme: minima
# 
gems:
 ## - jekyll-seo-tag
 ##- jekyll-press
exclude:
 - Gemfile
 - Gemfile.lock

# Google services
google_analytics: UA-72006658-2 
#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/ivli
 - title: LinkedIn
   url: https://www.linkedin.com/in/igorlikhachev
 - title: Runkeeper :)
   url: https://runkeeper.com/user/theIgorL  

#List of interesting Github repo/projects to include - optional
github:
 - ivli/roim 
 - ivli/Isolevels
 - ivli/ivli.github.io

hobbies:
 - skiing both alpine an XC, biking, skating (asphalt), reading, and I am an amateur guitar player

buildstatus: >
  [![Build Status](https://travis-ci.org/ivli/ivli.github.io.svg?branch=master)](https://travis-ci.org/ivli/ivli.github.io)

extras: ## https://drive.google.com/file/d/0B2iEehEHhN35TG5GNld6UEV5VXM/view?usp=drivesdk
